//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamespaceName
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", ConfigurationName = "NamespaceName.CellDownloadServiceV2")]
    public interface CellDownloadServiceV2
    {

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getFileInfosRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.getFileInfosResponse getFileInfos(NamespaceName.getFileInfosRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getFileInfosResponse> getFileInfosAsync(NamespaceName.getFileInfosRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message finishRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.finishResponse finish(NamespaceName.finishRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.finishResponse> finishAsync(NamespaceName.finishRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message downloadRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.downloadResponse download(NamespaceName.downloadRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.downloadResponse> downloadAsync(NamespaceName.downloadRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getNextRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.getNextResponse getNext(NamespaceName.getNextRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getNextResponse> getNextAsync(NamespaceName.getNextRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message downloadForVesselRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.downloadForVesselResponse downloadForVessel(NamespaceName.downloadForVesselRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.downloadForVesselResponse> downloadForVesselAsync(NamespaceName.downloadForVesselRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getCellKeysRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.getCellKeysResponse getCellKeys(NamespaceName.getCellKeysRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getCellKeysResponse> getCellKeysAsync(NamespaceName.getCellKeysRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.getResponse get(NamespaceName.getRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getResponse> getAsync(NamespaceName.getRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getSignatureRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellKey))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CellInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FileInfo))]
        NamespaceName.getSignatureResponse getSignature(NamespaceName.getSignatureRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getSignatureResponse> getSignatureAsync(NamespaceName.getSignatureRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class FileInfo
    {

        private string cacheKeyField;

        private string crcField;

        private string pathField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string cacheKey
        {
            get
            {
                return this.cacheKeyField;
            }
            set
            {
                this.cacheKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string crc
        {
            get
            {
                return this.crcField;
            }
            set
            {
                this.crcField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class CellKey
    {

        private string cellIdField;

        private System.Nullable<int> edtnField;

        private string permitField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string cellId
        {
            get
            {
                return this.cellIdField;
            }
            set
            {
                this.cellIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> edtn
        {
            get
            {
                return this.edtnField;
            }
            set
            {
                this.edtnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string permit
        {
            get
            {
                return this.permitField;
            }
            set
            {
                this.permitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class FileDownloadWrapper
    {

        private string cacheKeyField;

        private byte[] dataField;

        private string pathField;

        private int percentCompleteField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string cacheKey
        {
            get
            {
                return this.cacheKeyField;
            }
            set
            {
                this.cacheKeyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType = "base64Binary", IsNullable = true)]
        public byte[] data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public int percentComplete
        {
            get
            {
                return this.percentCompleteField;
            }
            set
            {
                this.percentCompleteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class CellInfo
    {

        private string cellIdField;

        private int edtnField;

        private int reissueField;

        private int updnField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string cellId
        {
            get
            {
                return this.cellIdField;
            }
            set
            {
                this.cellIdField = value;
            }
        }

        /// <remarks/>
        public int edtn
        {
            get
            {
                return this.edtnField;
            }
            set
            {
                this.edtnField = value;
            }
        }

        /// <remarks/>
        public int reissue
        {
            get
            {
                return this.reissueField;
            }
            set
            {
                this.reissueField = value;
            }
        }

        /// <remarks/>
        public int updn
        {
            get
            {
                return this.updnField;
            }
            set
            {
                this.updnField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getFileInfos", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getFileInfosRequest
    {

        public getFileInfosRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getFileInfosResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class getFileInfosResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.FileInfo[] getFileInfosReturn;

        public getFileInfosResponse()
        {
        }

        public getFileInfosResponse(NamespaceName.FileInfo[] getFileInfosReturn)
        {
            this.getFileInfosReturn = getFileInfosReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "finish", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class finishRequest
    {

        public finishRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "finishResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class finishResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool finishReturn;

        public finishResponse()
        {
        }

        public finishResponse(bool finishReturn)
        {
            this.finishReturn = finishReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "download", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class downloadRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool encrypted;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public System.DateTime fromDate;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public System.DateTime exportDate;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public string[] cellIds;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public NamespaceName.CellInfo[] status;

        public downloadRequest()
        {
        }

        public downloadRequest(bool encrypted, System.DateTime fromDate, System.DateTime exportDate, string[] cellIds, NamespaceName.CellInfo[] status)
        {
            this.encrypted = encrypted;
            this.fromDate = fromDate;
            this.exportDate = exportDate;
            this.cellIds = cellIds;
            this.status = status;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "downloadResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class downloadResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool downloadReturn;

        public downloadResponse()
        {
        }

        public downloadResponse(bool downloadReturn)
        {
            this.downloadReturn = downloadReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getNext", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getNextRequest
    {

        public getNextRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getNextResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class getNextResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.FileDownloadWrapper getNextReturn;

        public getNextResponse()
        {
        }

        public getNextResponse(NamespaceName.FileDownloadWrapper getNextReturn)
        {
            this.getNextReturn = getNextReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "downloadForVessel", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class downloadForVesselRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int vesselId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public bool encrypted;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public System.DateTime fromDate;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public bool ignoreDenied;

        public downloadForVesselRequest()
        {
        }

        public downloadForVesselRequest(int vesselId, bool encrypted, System.DateTime fromDate, bool ignoreDenied)
        {
            this.vesselId = vesselId;
            this.encrypted = encrypted;
            this.fromDate = fromDate;
            this.ignoreDenied = ignoreDenied;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "downloadForVesselResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class downloadForVesselResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool downloadForVesselReturn;

        public downloadForVesselResponse()
        {
        }

        public downloadForVesselResponse(bool downloadForVesselReturn)
        {
            this.downloadForVesselReturn = downloadForVesselReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCellKeys", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getCellKeysRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public System.DateTime exportDate;

        public getCellKeysRequest()
        {
        }

        public getCellKeysRequest(System.DateTime exportDate)
        {
            this.exportDate = exportDate;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getCellKeysResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class getCellKeysResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.CellKey[] getCellKeysReturn;

        public getCellKeysResponse()
        {
        }

        public getCellKeysResponse(NamespaceName.CellKey[] getCellKeysReturn)
        {
            this.getCellKeysReturn = getCellKeysReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "get", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int index;

        public getRequest()
        {
        }

        public getRequest(int index)
        {
            this.index = index;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class getResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.FileDownloadWrapper getReturn;

        public getResponse()
        {
        }

        public getResponse(NamespaceName.FileDownloadWrapper getReturn)
        {
            this.getReturn = getReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getSignature", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getSignatureRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public string cellId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public int edtn;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public int updn;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 3)]
        public int reissue;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 4)]
        public string certificateFileName;

        public getSignatureRequest()
        {
        }

        public getSignatureRequest(string cellId, int edtn, int updn, int reissue, string certificateFileName)
        {
            this.cellId = cellId;
            this.edtn = edtn;
            this.updn = updn;
            this.reissue = reissue;
            this.certificateFileName = certificateFileName;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getSignatureResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/CellDownloadServiceV2", IsWrapped = true)]
    public partial class getSignatureResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.FileDownloadWrapper getSignatureReturn;

        public getSignatureResponse()
        {
        }

        public getSignatureResponse(NamespaceName.FileDownloadWrapper getSignatureReturn)
        {
            this.getSignatureReturn = getSignatureReturn;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CellDownloadServiceV2Channel : NamespaceName.CellDownloadServiceV2, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CellDownloadServiceV2Client : System.ServiceModel.ClientBase<NamespaceName.CellDownloadServiceV2>, NamespaceName.CellDownloadServiceV2
    {

        public CellDownloadServiceV2Client()
        {
        }

        public CellDownloadServiceV2Client(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CellDownloadServiceV2Client(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CellDownloadServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CellDownloadServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getFileInfosResponse NamespaceName.CellDownloadServiceV2.getFileInfos(NamespaceName.getFileInfosRequest request)
        {
            return base.Channel.getFileInfos(request);
        }

        public NamespaceName.FileInfo[] getFileInfos()
        {
            NamespaceName.getFileInfosRequest inValue = new NamespaceName.getFileInfosRequest();
            NamespaceName.getFileInfosResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).getFileInfos(inValue);
            return retVal.getFileInfosReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getFileInfosResponse> NamespaceName.CellDownloadServiceV2.getFileInfosAsync(NamespaceName.getFileInfosRequest request)
        {
            return base.Channel.getFileInfosAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getFileInfosResponse> getFileInfosAsync()
        {
            NamespaceName.getFileInfosRequest inValue = new NamespaceName.getFileInfosRequest();
            return ((NamespaceName.CellDownloadServiceV2)(this)).getFileInfosAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.finishResponse NamespaceName.CellDownloadServiceV2.finish(NamespaceName.finishRequest request)
        {
            return base.Channel.finish(request);
        }

        public bool finish()
        {
            NamespaceName.finishRequest inValue = new NamespaceName.finishRequest();
            NamespaceName.finishResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).finish(inValue);
            return retVal.finishReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.finishResponse> NamespaceName.CellDownloadServiceV2.finishAsync(NamespaceName.finishRequest request)
        {
            return base.Channel.finishAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.finishResponse> finishAsync()
        {
            NamespaceName.finishRequest inValue = new NamespaceName.finishRequest();
            return ((NamespaceName.CellDownloadServiceV2)(this)).finishAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.downloadResponse NamespaceName.CellDownloadServiceV2.download(NamespaceName.downloadRequest request)
        {
            return base.Channel.download(request);
        }

        public bool download(bool encrypted, System.DateTime fromDate, System.DateTime exportDate, string[] cellIds, NamespaceName.CellInfo[] status)
        {
            NamespaceName.downloadRequest inValue = new NamespaceName.downloadRequest();
            inValue.encrypted = encrypted;
            inValue.fromDate = fromDate;
            inValue.exportDate = exportDate;
            inValue.cellIds = cellIds;
            inValue.status = status;
            NamespaceName.downloadResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).download(inValue);
            return retVal.downloadReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.downloadResponse> NamespaceName.CellDownloadServiceV2.downloadAsync(NamespaceName.downloadRequest request)
        {
            return base.Channel.downloadAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.downloadResponse> downloadAsync(bool encrypted, System.DateTime fromDate, System.DateTime exportDate, string[] cellIds, NamespaceName.CellInfo[] status)
        {
            NamespaceName.downloadRequest inValue = new NamespaceName.downloadRequest();
            inValue.encrypted = encrypted;
            inValue.fromDate = fromDate;
            inValue.exportDate = exportDate;
            inValue.cellIds = cellIds;
            inValue.status = status;
            return ((NamespaceName.CellDownloadServiceV2)(this)).downloadAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getNextResponse NamespaceName.CellDownloadServiceV2.getNext(NamespaceName.getNextRequest request)
        {
            return base.Channel.getNext(request);
        }

        public NamespaceName.FileDownloadWrapper getNext()
        {
            NamespaceName.getNextRequest inValue = new NamespaceName.getNextRequest();
            NamespaceName.getNextResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).getNext(inValue);
            return retVal.getNextReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getNextResponse> NamespaceName.CellDownloadServiceV2.getNextAsync(NamespaceName.getNextRequest request)
        {
            return base.Channel.getNextAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getNextResponse> getNextAsync()
        {
            NamespaceName.getNextRequest inValue = new NamespaceName.getNextRequest();
            return ((NamespaceName.CellDownloadServiceV2)(this)).getNextAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.downloadForVesselResponse NamespaceName.CellDownloadServiceV2.downloadForVessel(NamespaceName.downloadForVesselRequest request)
        {
            return base.Channel.downloadForVessel(request);
        }

        public bool downloadForVessel(int vesselId, bool encrypted, System.DateTime fromDate, bool ignoreDenied)
        {
            NamespaceName.downloadForVesselRequest inValue = new NamespaceName.downloadForVesselRequest();
            inValue.vesselId = vesselId;
            inValue.encrypted = encrypted;
            inValue.fromDate = fromDate;
            inValue.ignoreDenied = ignoreDenied;
            NamespaceName.downloadForVesselResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).downloadForVessel(inValue);
            return retVal.downloadForVesselReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.downloadForVesselResponse> NamespaceName.CellDownloadServiceV2.downloadForVesselAsync(NamespaceName.downloadForVesselRequest request)
        {
            return base.Channel.downloadForVesselAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.downloadForVesselResponse> downloadForVesselAsync(int vesselId, bool encrypted, System.DateTime fromDate, bool ignoreDenied)
        {
            NamespaceName.downloadForVesselRequest inValue = new NamespaceName.downloadForVesselRequest();
            inValue.vesselId = vesselId;
            inValue.encrypted = encrypted;
            inValue.fromDate = fromDate;
            inValue.ignoreDenied = ignoreDenied;
            return ((NamespaceName.CellDownloadServiceV2)(this)).downloadForVesselAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getCellKeysResponse NamespaceName.CellDownloadServiceV2.getCellKeys(NamespaceName.getCellKeysRequest request)
        {
            return base.Channel.getCellKeys(request);
        }

        public NamespaceName.CellKey[] getCellKeys(System.DateTime exportDate)
        {
            NamespaceName.getCellKeysRequest inValue = new NamespaceName.getCellKeysRequest();
            inValue.exportDate = exportDate;
            NamespaceName.getCellKeysResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).getCellKeys(inValue);
            return retVal.getCellKeysReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getCellKeysResponse> NamespaceName.CellDownloadServiceV2.getCellKeysAsync(NamespaceName.getCellKeysRequest request)
        {
            return base.Channel.getCellKeysAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getCellKeysResponse> getCellKeysAsync(System.DateTime exportDate)
        {
            NamespaceName.getCellKeysRequest inValue = new NamespaceName.getCellKeysRequest();
            inValue.exportDate = exportDate;
            return ((NamespaceName.CellDownloadServiceV2)(this)).getCellKeysAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getResponse NamespaceName.CellDownloadServiceV2.get(NamespaceName.getRequest request)
        {
            return base.Channel.get(request);
        }

        public NamespaceName.FileDownloadWrapper get(int index)
        {
            NamespaceName.getRequest inValue = new NamespaceName.getRequest();
            inValue.index = index;
            NamespaceName.getResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).get(inValue);
            return retVal.getReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getResponse> NamespaceName.CellDownloadServiceV2.getAsync(NamespaceName.getRequest request)
        {
            return base.Channel.getAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getResponse> getAsync(int index)
        {
            NamespaceName.getRequest inValue = new NamespaceName.getRequest();
            inValue.index = index;
            return ((NamespaceName.CellDownloadServiceV2)(this)).getAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getSignatureResponse NamespaceName.CellDownloadServiceV2.getSignature(NamespaceName.getSignatureRequest request)
        {
            return base.Channel.getSignature(request);
        }

        public NamespaceName.FileDownloadWrapper getSignature(string cellId, int edtn, int updn, int reissue, string certificateFileName)
        {
            NamespaceName.getSignatureRequest inValue = new NamespaceName.getSignatureRequest();
            inValue.cellId = cellId;
            inValue.edtn = edtn;
            inValue.updn = updn;
            inValue.reissue = reissue;
            inValue.certificateFileName = certificateFileName;
            NamespaceName.getSignatureResponse retVal = ((NamespaceName.CellDownloadServiceV2)(this)).getSignature(inValue);
            return retVal.getSignatureReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getSignatureResponse> NamespaceName.CellDownloadServiceV2.getSignatureAsync(NamespaceName.getSignatureRequest request)
        {
            return base.Channel.getSignatureAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getSignatureResponse> getSignatureAsync(string cellId, int edtn, int updn, int reissue, string certificateFileName)
        {
            NamespaceName.getSignatureRequest inValue = new NamespaceName.getSignatureRequest();
            inValue.cellId = cellId;
            inValue.edtn = edtn;
            inValue.updn = updn;
            inValue.reissue = reissue;
            inValue.certificateFileName = certificateFileName;
            return ((NamespaceName.CellDownloadServiceV2)(this)).getSignatureAsync(inValue);
        }
    }
}

