//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamespaceName
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", ConfigurationName = "NamespaceName.OrderServiceV2")]
    public interface OrderServiceV2
    {

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message updateOrderReportDistMarginRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        NamespaceName.updateOrderReportDistMarginResponse updateOrderReportDistMargin(NamespaceName.updateOrderReportDistMarginRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.updateOrderReportDistMarginResponse> updateOrderReportDistMarginAsync(NamespaceName.updateOrderReportDistMarginRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message placeOrderSENCRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.placeOrderSENCResponse placeOrderSENC(NamespaceName.placeOrderSENCRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.placeOrderSENCResponse> placeOrderSENCAsync(NamespaceName.placeOrderSENCRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message activateOrderAndSendPermitsByMailRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.activateOrderAndSendPermitsByMailResponse activateOrderAndSendPermitsByMail(NamespaceName.activateOrderAndSendPermitsByMailRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.activateOrderAndSendPermitsByMailResponse> activateOrderAndSendPermitsByMailAsync(NamespaceName.activateOrderAndSendPermitsByMailRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message activateOrderAndSendPermitsByMailForYearAndWeekRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekResponse activateOrderAndSendPermitsByMailForYearAndWeek(NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekResponse> activateOrderAndSendPermitsByMailForYearAndWeekAsync(NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message placeOrderRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.placeOrderResponse placeOrder(NamespaceName.placeOrderRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.placeOrderResponse> placeOrderAsync(NamespaceName.placeOrderRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message activateOrderRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.activateOrderResponse activateOrder(NamespaceName.activateOrderRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.activateOrderResponse> activateOrderAsync(NamespaceName.activateOrderRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message cancelOrderRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.cancelOrderResponse cancelOrder(NamespaceName.cancelOrderRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.cancelOrderResponse> cancelOrderAsync(NamespaceName.cancelOrderRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getOrderReportRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.getOrderReportResponse getOrderReport(NamespaceName.getOrderReportRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getOrderReportResponse> getOrderReportAsync(NamespaceName.getOrderReportRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.gds.ecc.no) of message getIsQuotationRequest does not match the default value (https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductReport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PermitEndDateRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OrderProductRequest))]
        NamespaceName.getIsQuotationResponse getIsQuotation(NamespaceName.getIsQuotationRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<NamespaceName.getIsQuotationResponse> getIsQuotationAsync(NamespaceName.getIsQuotationRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateOrderReportDistMargin", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class updateOrderReportDistMarginRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public decimal percent;

        public updateOrderReportDistMarginRequest()
        {
        }

        public updateOrderReportDistMarginRequest(int orderId, decimal percent)
        {
            this.orderId = orderId;
            this.percent = percent;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "updateOrderReportDistMarginResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class updateOrderReportDistMarginResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool updateOrderReportDistMarginReturn;

        public updateOrderReportDistMarginResponse()
        {
        }

        public updateOrderReportDistMarginResponse(bool updateOrderReportDistMarginReturn)
        {
            this.updateOrderReportDistMarginReturn = updateOrderReportDistMarginReturn;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class OrderRequest
    {

        private string additionalEmailField;

        private OrderProductRequest[] orderProductsField;

        private PermitEndDateRequest[] permitEndDateRequestsField;

        private string referenceNumberField;

        private string userIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string additionalEmail
        {
            get
            {
                return this.additionalEmailField;
            }
            set
            {
                this.additionalEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public OrderProductRequest[] orderProducts
        {
            get
            {
                return this.orderProductsField;
            }
            set
            {
                this.orderProductsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public PermitEndDateRequest[] permitEndDateRequests
        {
            get
            {
                return this.permitEndDateRequestsField;
            }
            set
            {
                this.permitEndDateRequestsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class OrderProductRequest
    {

        private string productIdField;

        private System.Nullable<int> quantityField;

        private System.Nullable<int> subscriptionTypeIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> subscriptionTypeId
        {
            get
            {
                return this.subscriptionTypeIdField;
            }
            set
            {
                this.subscriptionTypeIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class OrderProductReport
    {

        private System.Nullable<int> countryIdField;

        private System.Nullable<decimal> discountedPriceField;

        private System.Nullable<decimal> distributorRetailPriceField;

        private System.Nullable<System.DateTime> permitEndDateField;

        private string priceBandNameField;

        private System.Nullable<decimal> productDiscountField;

        private string productIdField;

        private System.Nullable<decimal> productPriceField;

        private string productTypeNameField;

        private System.Nullable<int> quantityField;

        private string subscriptionTypeNameField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> countryId
        {
            get
            {
                return this.countryIdField;
            }
            set
            {
                this.countryIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> discountedPrice
        {
            get
            {
                return this.discountedPriceField;
            }
            set
            {
                this.discountedPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> distributorRetailPrice
        {
            get
            {
                return this.distributorRetailPriceField;
            }
            set
            {
                this.distributorRetailPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> permitEndDate
        {
            get
            {
                return this.permitEndDateField;
            }
            set
            {
                this.permitEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string priceBandName
        {
            get
            {
                return this.priceBandNameField;
            }
            set
            {
                this.priceBandNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> productDiscount
        {
            get
            {
                return this.productDiscountField;
            }
            set
            {
                this.productDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> productPrice
        {
            get
            {
                return this.productPriceField;
            }
            set
            {
                this.productPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string productTypeName
        {
            get
            {
                return this.productTypeNameField;
            }
            set
            {
                this.productTypeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string subscriptionTypeName
        {
            get
            {
                return this.subscriptionTypeNameField;
            }
            set
            {
                this.subscriptionTypeNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class OrderReport
    {

        private System.Nullable<int> customerDiscountField;

        private string customerNameField;

        private System.Nullable<int> discountQuantityField;

        private System.Nullable<int> distributorDiscountField;

        private string distributorDiscountGroupNameField;

        private System.Nullable<decimal> distributorMarginPercentField;

        private string distributorNameField;

        private System.Nullable<System.DateTime> orderDateField;

        private System.Nullable<int> orderIdField;

        private OrderProductReport[] orderProductsField;

        private string referenceNumberField;

        private System.Nullable<decimal> totalDiscountedPriceField;

        private System.Nullable<decimal> totalProductDiscountField;

        private System.Nullable<decimal> totalProductPriceField;

        private string vesselNameField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> customerDiscount
        {
            get
            {
                return this.customerDiscountField;
            }
            set
            {
                this.customerDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string customerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> discountQuantity
        {
            get
            {
                return this.discountQuantityField;
            }
            set
            {
                this.discountQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> distributorDiscount
        {
            get
            {
                return this.distributorDiscountField;
            }
            set
            {
                this.distributorDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string distributorDiscountGroupName
        {
            get
            {
                return this.distributorDiscountGroupNameField;
            }
            set
            {
                this.distributorDiscountGroupNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> distributorMarginPercent
        {
            get
            {
                return this.distributorMarginPercentField;
            }
            set
            {
                this.distributorMarginPercentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string distributorName
        {
            get
            {
                return this.distributorNameField;
            }
            set
            {
                this.distributorNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> orderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public OrderProductReport[] orderProducts
        {
            get
            {
                return this.orderProductsField;
            }
            set
            {
                this.orderProductsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> totalDiscountedPrice
        {
            get
            {
                return this.totalDiscountedPriceField;
            }
            set
            {
                this.totalDiscountedPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> totalProductDiscount
        {
            get
            {
                return this.totalProductDiscountField;
            }
            set
            {
                this.totalProductDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> totalProductPrice
        {
            get
            {
                return this.totalProductPriceField;
            }
            set
            {
                this.totalProductPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vesselName
        {
            get
            {
                return this.vesselNameField;
            }
            set
            {
                this.vesselNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:BeanService")]
    public partial class PermitEndDateRequest
    {

        private System.Nullable<System.DateTime> requestedEndDateField;

        private System.Nullable<int> subscriptionTypeIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> requestedEndDate
        {
            get
            {
                return this.requestedEndDateField;
            }
            set
            {
                this.requestedEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<int> subscriptionTypeId
        {
            get
            {
                return this.subscriptionTypeIdField;
            }
            set
            {
                this.subscriptionTypeIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "placeOrderSENC", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class placeOrderSENCRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.OrderRequest orderRequest;

        public placeOrderSENCRequest()
        {
        }

        public placeOrderSENCRequest(NamespaceName.OrderRequest orderRequest)
        {
            this.orderRequest = orderRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "placeOrderSENCResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class placeOrderSENCResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int placeOrderSENCReturn;

        public placeOrderSENCResponse()
        {
        }

        public placeOrderSENCResponse(int placeOrderSENCReturn)
        {
            this.placeOrderSENCReturn = placeOrderSENCReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "activateOrderAndSendPermitsByMail", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class activateOrderAndSendPermitsByMailRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        public activateOrderAndSendPermitsByMailRequest()
        {
        }

        public activateOrderAndSendPermitsByMailRequest(int orderId)
        {
            this.orderId = orderId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "activateOrderAndSendPermitsByMailResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class activateOrderAndSendPermitsByMailResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool activateOrderAndSendPermitsByMailReturn;

        public activateOrderAndSendPermitsByMailResponse()
        {
        }

        public activateOrderAndSendPermitsByMailResponse(bool activateOrderAndSendPermitsByMailReturn)
        {
            this.activateOrderAndSendPermitsByMailReturn = activateOrderAndSendPermitsByMailReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "activateOrderAndSendPermitsByMailForYearAndWeek", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class activateOrderAndSendPermitsByMailForYearAndWeekRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 1)]
        public int year;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 2)]
        public int week;

        public activateOrderAndSendPermitsByMailForYearAndWeekRequest()
        {
        }

        public activateOrderAndSendPermitsByMailForYearAndWeekRequest(int orderId, int year, int week)
        {
            this.orderId = orderId;
            this.year = year;
            this.week = week;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "activateOrderAndSendPermitsByMailForYearAndWeekResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class activateOrderAndSendPermitsByMailForYearAndWeekResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool activateOrderAndSendPermitsByMailForYearAndWeekReturn;

        public activateOrderAndSendPermitsByMailForYearAndWeekResponse()
        {
        }

        public activateOrderAndSendPermitsByMailForYearAndWeekResponse(bool activateOrderAndSendPermitsByMailForYearAndWeekReturn)
        {
            this.activateOrderAndSendPermitsByMailForYearAndWeekReturn = activateOrderAndSendPermitsByMailForYearAndWeekReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "placeOrder", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class placeOrderRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.OrderRequest orderRequest;

        public placeOrderRequest()
        {
        }

        public placeOrderRequest(NamespaceName.OrderRequest orderRequest)
        {
            this.orderRequest = orderRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "placeOrderResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class placeOrderResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int placeOrderReturn;

        public placeOrderResponse()
        {
        }

        public placeOrderResponse(int placeOrderReturn)
        {
            this.placeOrderReturn = placeOrderReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "activateOrder", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class activateOrderRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        public activateOrderRequest()
        {
        }

        public activateOrderRequest(int orderId)
        {
            this.orderId = orderId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "activateOrderResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class activateOrderResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool activateOrderReturn;

        public activateOrderResponse()
        {
        }

        public activateOrderResponse(bool activateOrderReturn)
        {
            this.activateOrderReturn = activateOrderReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "cancelOrder", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class cancelOrderRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        public cancelOrderRequest()
        {
        }

        public cancelOrderRequest(int orderId)
        {
            this.orderId = orderId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "cancelOrderResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class cancelOrderResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool cancelOrderReturn;

        public cancelOrderResponse()
        {
        }

        public cancelOrderResponse(bool cancelOrderReturn)
        {
            this.cancelOrderReturn = cancelOrderReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getOrderReport", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getOrderReportRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        public getOrderReportRequest()
        {
        }

        public getOrderReportRequest(int orderId)
        {
            this.orderId = orderId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getOrderReportResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class getOrderReportResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public NamespaceName.OrderReport getOrderReportReturn;

        public getOrderReportResponse()
        {
        }

        public getOrderReportResponse(NamespaceName.OrderReport getOrderReportReturn)
        {
            this.getOrderReportReturn = getOrderReportReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getIsQuotation", WrapperNamespace = "http://ws.gds.ecc.no", IsWrapped = true)]
    public partial class getIsQuotationRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public int orderId;

        public getIsQuotationRequest()
        {
        }

        public getIsQuotationRequest(int orderId)
        {
            this.orderId = orderId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getIsQuotationResponse", WrapperNamespace = "https://qaprimar.ecc.no/qaprimar/services_basic/OrderServiceV2", IsWrapped = true)]
    public partial class getIsQuotationResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public bool getIsQuotationReturn;

        public getIsQuotationResponse()
        {
        }

        public getIsQuotationResponse(bool getIsQuotationReturn)
        {
            this.getIsQuotationReturn = getIsQuotationReturn;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceV2Channel : NamespaceName.OrderServiceV2, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceV2Client : System.ServiceModel.ClientBase<NamespaceName.OrderServiceV2>, NamespaceName.OrderServiceV2
    {

        public OrderServiceV2Client()
        {
        }

        public OrderServiceV2Client(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public OrderServiceV2Client(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrderServiceV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public OrderServiceV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.updateOrderReportDistMarginResponse NamespaceName.OrderServiceV2.updateOrderReportDistMargin(NamespaceName.updateOrderReportDistMarginRequest request)
        {
            return base.Channel.updateOrderReportDistMargin(request);
        }

        public bool updateOrderReportDistMargin(int orderId, decimal percent)
        {
            NamespaceName.updateOrderReportDistMarginRequest inValue = new NamespaceName.updateOrderReportDistMarginRequest();
            inValue.orderId = orderId;
            inValue.percent = percent;
            NamespaceName.updateOrderReportDistMarginResponse retVal = ((NamespaceName.OrderServiceV2)(this)).updateOrderReportDistMargin(inValue);
            return retVal.updateOrderReportDistMarginReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.updateOrderReportDistMarginResponse> NamespaceName.OrderServiceV2.updateOrderReportDistMarginAsync(NamespaceName.updateOrderReportDistMarginRequest request)
        {
            return base.Channel.updateOrderReportDistMarginAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.updateOrderReportDistMarginResponse> updateOrderReportDistMarginAsync(int orderId, decimal percent)
        {
            NamespaceName.updateOrderReportDistMarginRequest inValue = new NamespaceName.updateOrderReportDistMarginRequest();
            inValue.orderId = orderId;
            inValue.percent = percent;
            return ((NamespaceName.OrderServiceV2)(this)).updateOrderReportDistMarginAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.placeOrderSENCResponse NamespaceName.OrderServiceV2.placeOrderSENC(NamespaceName.placeOrderSENCRequest request)
        {
            return base.Channel.placeOrderSENC(request);
        }

        public int placeOrderSENC(NamespaceName.OrderRequest orderRequest)
        {
            NamespaceName.placeOrderSENCRequest inValue = new NamespaceName.placeOrderSENCRequest();
            inValue.orderRequest = orderRequest;
            NamespaceName.placeOrderSENCResponse retVal = ((NamespaceName.OrderServiceV2)(this)).placeOrderSENC(inValue);
            return retVal.placeOrderSENCReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.placeOrderSENCResponse> NamespaceName.OrderServiceV2.placeOrderSENCAsync(NamespaceName.placeOrderSENCRequest request)
        {
            return base.Channel.placeOrderSENCAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.placeOrderSENCResponse> placeOrderSENCAsync(NamespaceName.OrderRequest orderRequest)
        {
            NamespaceName.placeOrderSENCRequest inValue = new NamespaceName.placeOrderSENCRequest();
            inValue.orderRequest = orderRequest;
            return ((NamespaceName.OrderServiceV2)(this)).placeOrderSENCAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.activateOrderAndSendPermitsByMailResponse NamespaceName.OrderServiceV2.activateOrderAndSendPermitsByMail(NamespaceName.activateOrderAndSendPermitsByMailRequest request)
        {
            return base.Channel.activateOrderAndSendPermitsByMail(request);
        }

        public bool activateOrderAndSendPermitsByMail(int orderId)
        {
            NamespaceName.activateOrderAndSendPermitsByMailRequest inValue = new NamespaceName.activateOrderAndSendPermitsByMailRequest();
            inValue.orderId = orderId;
            NamespaceName.activateOrderAndSendPermitsByMailResponse retVal = ((NamespaceName.OrderServiceV2)(this)).activateOrderAndSendPermitsByMail(inValue);
            return retVal.activateOrderAndSendPermitsByMailReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.activateOrderAndSendPermitsByMailResponse> NamespaceName.OrderServiceV2.activateOrderAndSendPermitsByMailAsync(NamespaceName.activateOrderAndSendPermitsByMailRequest request)
        {
            return base.Channel.activateOrderAndSendPermitsByMailAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.activateOrderAndSendPermitsByMailResponse> activateOrderAndSendPermitsByMailAsync(int orderId)
        {
            NamespaceName.activateOrderAndSendPermitsByMailRequest inValue = new NamespaceName.activateOrderAndSendPermitsByMailRequest();
            inValue.orderId = orderId;
            return ((NamespaceName.OrderServiceV2)(this)).activateOrderAndSendPermitsByMailAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekResponse NamespaceName.OrderServiceV2.activateOrderAndSendPermitsByMailForYearAndWeek(NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest request)
        {
            return base.Channel.activateOrderAndSendPermitsByMailForYearAndWeek(request);
        }

        public bool activateOrderAndSendPermitsByMailForYearAndWeek(int orderId, int year, int week)
        {
            NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest inValue = new NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest();
            inValue.orderId = orderId;
            inValue.year = year;
            inValue.week = week;
            NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekResponse retVal = ((NamespaceName.OrderServiceV2)(this)).activateOrderAndSendPermitsByMailForYearAndWeek(inValue);
            return retVal.activateOrderAndSendPermitsByMailForYearAndWeekReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekResponse> NamespaceName.OrderServiceV2.activateOrderAndSendPermitsByMailForYearAndWeekAsync(NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest request)
        {
            return base.Channel.activateOrderAndSendPermitsByMailForYearAndWeekAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekResponse> activateOrderAndSendPermitsByMailForYearAndWeekAsync(int orderId, int year, int week)
        {
            NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest inValue = new NamespaceName.activateOrderAndSendPermitsByMailForYearAndWeekRequest();
            inValue.orderId = orderId;
            inValue.year = year;
            inValue.week = week;
            return ((NamespaceName.OrderServiceV2)(this)).activateOrderAndSendPermitsByMailForYearAndWeekAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.placeOrderResponse NamespaceName.OrderServiceV2.placeOrder(NamespaceName.placeOrderRequest request)
        {
            return base.Channel.placeOrder(request);
        }

        public int placeOrder(NamespaceName.OrderRequest orderRequest)
        {
            NamespaceName.placeOrderRequest inValue = new NamespaceName.placeOrderRequest();
            inValue.orderRequest = orderRequest;
            NamespaceName.placeOrderResponse retVal = ((NamespaceName.OrderServiceV2)(this)).placeOrder(inValue);
            return retVal.placeOrderReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.placeOrderResponse> NamespaceName.OrderServiceV2.placeOrderAsync(NamespaceName.placeOrderRequest request)
        {
            return base.Channel.placeOrderAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.placeOrderResponse> placeOrderAsync(NamespaceName.OrderRequest orderRequest)
        {
            NamespaceName.placeOrderRequest inValue = new NamespaceName.placeOrderRequest();
            inValue.orderRequest = orderRequest;
            return ((NamespaceName.OrderServiceV2)(this)).placeOrderAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.activateOrderResponse NamespaceName.OrderServiceV2.activateOrder(NamespaceName.activateOrderRequest request)
        {
            return base.Channel.activateOrder(request);
        }

        public bool activateOrder(int orderId)
        {
            NamespaceName.activateOrderRequest inValue = new NamespaceName.activateOrderRequest();
            inValue.orderId = orderId;
            NamespaceName.activateOrderResponse retVal = ((NamespaceName.OrderServiceV2)(this)).activateOrder(inValue);
            return retVal.activateOrderReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.activateOrderResponse> NamespaceName.OrderServiceV2.activateOrderAsync(NamespaceName.activateOrderRequest request)
        {
            return base.Channel.activateOrderAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.activateOrderResponse> activateOrderAsync(int orderId)
        {
            NamespaceName.activateOrderRequest inValue = new NamespaceName.activateOrderRequest();
            inValue.orderId = orderId;
            return ((NamespaceName.OrderServiceV2)(this)).activateOrderAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.cancelOrderResponse NamespaceName.OrderServiceV2.cancelOrder(NamespaceName.cancelOrderRequest request)
        {
            return base.Channel.cancelOrder(request);
        }

        public bool cancelOrder(int orderId)
        {
            NamespaceName.cancelOrderRequest inValue = new NamespaceName.cancelOrderRequest();
            inValue.orderId = orderId;
            NamespaceName.cancelOrderResponse retVal = ((NamespaceName.OrderServiceV2)(this)).cancelOrder(inValue);
            return retVal.cancelOrderReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.cancelOrderResponse> NamespaceName.OrderServiceV2.cancelOrderAsync(NamespaceName.cancelOrderRequest request)
        {
            return base.Channel.cancelOrderAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.cancelOrderResponse> cancelOrderAsync(int orderId)
        {
            NamespaceName.cancelOrderRequest inValue = new NamespaceName.cancelOrderRequest();
            inValue.orderId = orderId;
            return ((NamespaceName.OrderServiceV2)(this)).cancelOrderAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getOrderReportResponse NamespaceName.OrderServiceV2.getOrderReport(NamespaceName.getOrderReportRequest request)
        {
            return base.Channel.getOrderReport(request);
        }

        public NamespaceName.OrderReport getOrderReport(int orderId)
        {
            NamespaceName.getOrderReportRequest inValue = new NamespaceName.getOrderReportRequest();
            inValue.orderId = orderId;
            NamespaceName.getOrderReportResponse retVal = ((NamespaceName.OrderServiceV2)(this)).getOrderReport(inValue);
            return retVal.getOrderReportReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getOrderReportResponse> NamespaceName.OrderServiceV2.getOrderReportAsync(NamespaceName.getOrderReportRequest request)
        {
            return base.Channel.getOrderReportAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getOrderReportResponse> getOrderReportAsync(int orderId)
        {
            NamespaceName.getOrderReportRequest inValue = new NamespaceName.getOrderReportRequest();
            inValue.orderId = orderId;
            return ((NamespaceName.OrderServiceV2)(this)).getOrderReportAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NamespaceName.getIsQuotationResponse NamespaceName.OrderServiceV2.getIsQuotation(NamespaceName.getIsQuotationRequest request)
        {
            return base.Channel.getIsQuotation(request);
        }

        public bool getIsQuotation(int orderId)
        {
            NamespaceName.getIsQuotationRequest inValue = new NamespaceName.getIsQuotationRequest();
            inValue.orderId = orderId;
            NamespaceName.getIsQuotationResponse retVal = ((NamespaceName.OrderServiceV2)(this)).getIsQuotation(inValue);
            return retVal.getIsQuotationReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NamespaceName.getIsQuotationResponse> NamespaceName.OrderServiceV2.getIsQuotationAsync(NamespaceName.getIsQuotationRequest request)
        {
            return base.Channel.getIsQuotationAsync(request);
        }

        public System.Threading.Tasks.Task<NamespaceName.getIsQuotationResponse> getIsQuotationAsync(int orderId)
        {
            NamespaceName.getIsQuotationRequest inValue = new NamespaceName.getIsQuotationRequest();
            inValue.orderId = orderId;
            return ((NamespaceName.OrderServiceV2)(this)).getIsQuotationAsync(inValue);
        }
    }
}


